USER_NAME := twaauk
RGBLIGHT_ENABLE = yes
COMBO_ENABLE = yes
OLED_ENABLE = no

VIA_ENABLE = yes
LTO_ENABLE = yes
SPACE_CADET_ENABLE = no
MAGIC_ENABLE = no
TAPPING_TERM_PER_KEY = yes
TAP_DANCE_ENABLE = yes
